services:
  item-tracker:
    build:
      context: ./
      dockerfile: build/backend/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - "./itemtracker/:/app/itemtracker"
    restart: unless-stopped
    command: "python3 manage.py runserver 0.0.0.0:80"
    environment:
      - WORKER_COUNT=2
    # env_file:
    #   - .env
  # redis:
  #   image: redis
  #   restart: always