---
title: ItemTracker DB
---
erDiagram
    Company {
        uid id
        string name
    }

    Location {
        uid id
        string name
        string external_id
    }

    Item {
        uid id
        string external_id
        string url
    }

    ItemStock {
        uid id
        int stock
        fk location_id
        fk item_id
    }

    Company ||--o{ Location: has
    Location ||--o{ Item: stores
    Location ||--o{ ItemStock: has
    Item ||--o{ ItemStock: has 
